name: Clean Workflow Runs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 0'  # Every Sunday at 3 AM

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 7
          keep_minimum_runs: 3
